version: '2'

services:
  wordpress:
    image: wordpress:4.9.8-php5.6-apache
    # volumes:
    #   - .:/var/www/html/wp-content/themes/wp_base_theme
    #   - ./docker/plugins:/var/www/html/wp-content/plugins
    #   - ./docker/uploads:/var/www/html/wp-content/uploads
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_USER: wordpress
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306
    volumes:
      # - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  # console:
  #   image: onpointglobal/docker-webpack
  #   command: webpack --progress --color
  #   volumes:
  #     - .:/var/www/theme
  #   restart: always